version: '3'
services:

 db:
   image: mariadb
   volumes:
     - db_data:/var/lib/mysql
   environment:
    MYSQL_ROOT_PASSWORD: hello
    MYSQL_PASSWORD: hello
    MYSQL_USER: root
    MYSQL_DATABASE: rsvp
   networks:
    - rsvpnet
   ports:
    - 3306:3306
 web:
   build: . 
   ports:
    - "5000:5000"
   environment:
    TEXT1: Hackfest 
    TEXT2: Registration 
    ORGANIZER: UVCE
    MYSQL_HOST: mysql
    MYSQL_DB: rsvp
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
